// Copyright 2024 The Infrix Authors
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.

package evidence

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
)

// PortableEvidencePackageVersion is the canonical version string for
// the portable package wire format. Verifiers MUST reject packages
// whose Version field does not match. Pre-users: there is no support
// for prior versions.
//
// P1-005 closure (2026-05-02) bumped the wire format from "2" → "3"
// to add the PluginVersions + PolicyDecisionDigest + AnchorTxHash /
// AnchorBlockHeight cross-binding fields. Older packages cannot pass
// the new verifier and vice versa — pre-user, no backwards compat.
//
// platform-review-3 Epic 2 (2026-06) bumped "3" → "4" to add the
// optional ReplayCapsule field. A public-production bundle MUST carry
// a replay capsule so an independent party can deterministically
// re-execute the operation and confirm it reproduces; legacy bundles
// omit it. The capsule is committed to ExportHash so tampering it is
// caught offline.
const PortableEvidencePackageVersion = "4"

// PortableEvidencePackage is a self-contained, verifiable evidence
// package that can be verified offline without platform access. It
// bundles the evidence bundle, plan/outcome digests, trust snapshot,
// inclusion proofs, and anchor proof into a single exportable artifact.
//
// See PORTABLE_SPEC.md for the full canonical wire format and verifier
// contract. P1-005 closure (2026-05-02) added PluginVersions +
// PolicyDecisionDigest + AnchorTxHash / AnchorBlockHeight so the
// verifier can detect tampering of plan / outcome / policy / trust /
// anchor fields even when the attacker rehashes ExportHash.
type PortableEvidencePackage struct {
	// Version identifies the schema version. Verifiers reject any
	// value other than PortableEvidencePackageVersion.
	Version string `json:"version"`

	// BundleData is the canonicalJSON-encoded EvidenceBundle.
	BundleData json.RawMessage `json:"bundleData"`

	// PlanHash is the SHA-256 of the ExecutionPlan that was approved.
	// For subsystem-attributed bundles without approval evidence this
	// equals OutcomeDigest (artifact == outcome).
	PlanHash [32]byte `json:"planHash"`

	// OutcomeDigest is the deterministic digest of the canonical
	// OutcomeRecord referenced by the bundle.
	OutcomeDigest [32]byte `json:"outcomeDigest"`

	// TrustSnapshot captures the trust profile states at execution time.
	TrustSnapshot []TrustSnapshotEntry `json:"trustSnapshot,omitempty"`

	// InclusionProofs provides Merkle inclusion proofs for each
	// evidence chain link, enabling offline verification of chain
	// integrity.
	InclusionProofs []MerkleInclusionProof `json:"inclusionProofs,omitempty"`

	// AnchorProof contains the L0 anchor data when the embedded bundle
	// is anchored. Required when the embedded bundle's anchor status
	// is anchored or verified.
	AnchorProof *EvidenceAnchorData `json:"anchorProof,omitempty"`

	// AnchorTxHash mirrors EvidenceBundle.AnchorTxHash for cross-binding.
	// When the embedded bundle is anchored, the verifier asserts this
	// equals embedded.AnchorTxHash so swapping AnchorProof bytes is
	// caught even after the attacker rehashes ExportHash. P1-005
	// closure (2026-05-02).
	AnchorTxHash string `json:"anchorTxHash,omitempty"`

	// AnchorBlockHeight mirrors EvidenceBundle.AnchorBlock for cross-
	// binding. When the embedded bundle is anchored, the verifier
	// asserts this equals embedded.AnchorBlock. P1-005 closure.
	AnchorBlockHeight uint64 `json:"anchorBlockHeight,omitempty"`

	// PluginVersions enumerates the production plugins that produced
	// the bundle, with their canonical ImplementationHash so external
	// auditors can confirm the bundle was generated by known versions.
	// The verifier asserts the slice is non-nil for Full / Anchored
	// bundles (every production execution touches at least one
	// plugin); each entry carries enough fields for a third party to
	// re-derive the descriptor identity. P1-005 closure (2026-05-02).
	PluginVersions []PluginVersionEntry `json:"pluginVersions,omitempty"`

	// PolicyDecisionDigest binds the embedded bundle's PolicyDecisions
	// list to a single 32-byte commitment computed via canonical-JSON
	// over the decisions. Tampering ANY policy decision in the embedded
	// bundle changes both the bundle's BundleHash AND this digest, so
	// rehashing the ExportHash alone is insufficient to hide the
	// tamper. Zero when the bundle has no policy decisions. P1-005
	// closure (2026-05-02).
	PolicyDecisionDigest [32]byte `json:"policyDecisionDigest,omitempty"`

	// ReplayCapsule, when present, carries the deterministic-replay
	// material (runtime/build fingerprint, plugin inventory, plan /
	// intent / outcome hashes, pre/post state roots, deterministic
	// inputs, execution trace, L0 anchor coordinates) that lets an
	// independent party re-execute the operation and confirm it
	// reproduces the recorded outcome. The schema lives in
	// pkg/verifykit/replaycapsule; it is carried here as raw JSON so the
	// evidence layer stays schema-agnostic. It is committed to ExportHash
	// (see computePortableExportHash) so a tampered capsule fails the
	// offline integrity gate. Empty for legacy / non-production bundles.
	// platform-review-3 Epic 2 (2026-06).
	ReplayCapsule json.RawMessage `json:"replayCapsule,omitempty"`

	// WitnessReceipts carries independent witness attestations
	// (platform-review-3 Epic 5). Receipts are produced AFTER export by
	// parties other than the producing node, so they are NOT part of
	// ExportHash; each receipt is independently signed and cross-binds to
	// the bundle via its recorded outcome / capsule / anchor hashes. The
	// typed schema lives in pkg/witness; carried here as raw JSON.
	WitnessReceipts []json.RawMessage `json:"witnessReceipts,omitempty"`

	// ExportHash is the SHA-256 of all other fields, providing package
	// integrity verification.
	ExportHash [32]byte `json:"exportHash"`

	// Signature is an optional cryptographic signature over ExportHash.
	Signature []byte `json:"signature,omitempty"`
}

// PluginVersionEntry identifies one plugin descriptor that produced
// content in the embedded EvidenceBundle. Auditors compare the
// triple (PluginID, Version, ImplementationHash) against their
// own production-plugin inventory to confirm the bundle was
// generated by a known and approved plugin.
//
// P1-005 closure (2026-05-02): the milestone calls out "plugin
// versions" as one of the six things portable verification must
// cover. Carrying all three fields lets verifiers cross-check
// against either a published plugin manifest (PluginID + Version)
// or a pinned reproducible build (ImplementationHash) without
// renegotiating the schema.
type PluginVersionEntry struct {
	PluginID           string `json:"pluginId"`
	Version            string `json:"version"`
	ImplementationHash string `json:"implementationHash"`
}

// TrustSnapshotEntry captures one trust profile's state at a point in time.
//
// Spec §8.3 mandates the following fields for trust-consuming
// executions: profile IDs, states, freshness timestamps, finality
// assumptions, assumption class, and verifier IDs where relevant.
// The shape is mirrored in pkg/executor.TrustSnapshotEntry so the
// portable package round-trips without field remapping.
type TrustSnapshotEntry struct {
	ProfileID     string `json:"profileId"`
	Status        string `json:"status"` // active, degraded, suspended
	ProofType     string `json:"proofType"`
	Assumption    string `json:"assumption"`
	BlockHeight   uint64 `json:"blockHeight"`
	FreshnessAt   int64  `json:"freshnessAt,omitempty"`   // Spec §8.3 freshness timestamp (Unix seconds)
	FinalityModel string `json:"finalityModel,omitempty"` // Spec §8.3 finality assumption (§14.2 value)
	VerifierID    string `json:"verifierId,omitempty"`    // Spec §8.3 verifier ID where relevant
}

// BuildPortablePackageInputs aggregates every field BuildPortablePackage
// commits to the wire. The struct shape exists so future closures can
// add fields without breaking the existing call sites — adding a new
// field requires populating it on the input struct, not adjusting
// every caller's positional arguments. P1-005 closure (2026-05-02).
type BuildPortablePackageInputs struct {
	BundleData       json.RawMessage
	PlanHash         [32]byte
	OutcomeDigest    [32]byte
	TrustSnapshot    []TrustSnapshotEntry
	InclusionProofs  []MerkleInclusionProof
	AnchorProof      *EvidenceAnchorData
	AnchorTxHash     string
	AnchorBlock      uint64
	PluginVersions   []PluginVersionEntry
	PolicyDecisions  []DecisionProofRef
	// ReplayCapsule is the optional deterministic-replay material
	// (raw JSON; schema in pkg/verifykit/replaycapsule). platform-review-3
	// Epic 2.
	ReplayCapsule json.RawMessage
}

// BuildPortablePackage creates a PortableEvidencePackage from the given
// components. It computes the ExportHash from all included data using
// the canonical encoding rules in PORTABLE_SPEC.md. Retained as a
// thin wrapper over BuildPortablePackageWithBindings for callers that
// don't want to populate the P1-005 cross-binding fields explicitly.
func BuildPortablePackage(
	bundleData json.RawMessage,
	planHash [32]byte,
	outcomeDigest [32]byte,
	trustSnapshot []TrustSnapshotEntry,
	inclusionProofs []MerkleInclusionProof,
	anchorProof *EvidenceAnchorData,
) (*PortableEvidencePackage, error) {
	return BuildPortablePackageWithBindings(BuildPortablePackageInputs{
		BundleData:      bundleData,
		PlanHash:        planHash,
		OutcomeDigest:   outcomeDigest,
		TrustSnapshot:   trustSnapshot,
		InclusionProofs: inclusionProofs,
		AnchorProof:     anchorProof,
	})
}

// BuildPortablePackageWithBindings is the canonical builder. It
// populates every field including the P1-005 cross-binding surface
// (PluginVersions, PolicyDecisionDigest, AnchorTxHash,
// AnchorBlockHeight) so the verifier can detect tampering even after
// the attacker rehashes ExportHash.
func BuildPortablePackageWithBindings(in BuildPortablePackageInputs) (*PortableEvidencePackage, error) {
	pkg := &PortableEvidencePackage{
		Version:           PortableEvidencePackageVersion,
		BundleData:        in.BundleData,
		PlanHash:          in.PlanHash,
		OutcomeDigest:     in.OutcomeDigest,
		TrustSnapshot:     in.TrustSnapshot,
		InclusionProofs:   in.InclusionProofs,
		AnchorProof:       in.AnchorProof,
		AnchorTxHash:      in.AnchorTxHash,
		AnchorBlockHeight: in.AnchorBlock,
		PluginVersions:    in.PluginVersions,
		ReplayCapsule:     in.ReplayCapsule,
	}
	if len(in.PolicyDecisions) > 0 {
		digest, derr := computePolicyDecisionDigest(in.PolicyDecisions)
		if derr != nil {
			return nil, fmt.Errorf("evidence: compute policy decision digest: %w", derr)
		}
		pkg.PolicyDecisionDigest = digest
	}
	hash, err := computePortableExportHash(pkg)
	if err != nil {
		return nil, fmt.Errorf("evidence: compute export hash: %w", err)
	}
	pkg.ExportHash = hash
	return pkg, nil
}

// computePolicyDecisionDigest is the canonical commitment for a
// policy-decision slice. canonicalJSON guarantees byte-stable
// encoding so the same slice always produces the same digest across
// runs and implementations. Empty slice returns a zero digest so
// callers can short-circuit the verifier branch.
func computePolicyDecisionDigest(decisions []DecisionProofRef) ([32]byte, error) {
	if len(decisions) == 0 {
		return [32]byte{}, nil
	}
	canonical, err := canonicalJSON(decisions)
	if err != nil {
		return [32]byte{}, err
	}
	return sha256.Sum256(canonical), nil
}

// VerifyPortablePackage performs a strict, offline verification of a
// portable evidence package. Gap 8 sub-gap B + P1-005 closure: every
// check is fail-loud — there are no warnings.
//
// Verification steps (P1-005 closure adds steps 9-12 so every field
// the milestone names — plan hash, outcome hash, plugin versions,
// policy decision proofs, trust snapshots, anchor inclusion — is
// cross-bound to the embedded bundle. Tampering any of them and
// rehashing ExportHash still fails verification because the embedded
// bundle's BundleHash + this verifier's cross-checks give multiple
// independent witnesses for each field):
//
//  1. Package is non-nil and Version matches.
//  2. ExportHash recomputes to the value stored in the package.
//  3. BundleData is non-empty and parses as a valid EvidenceBundle.
//  4. PlanHash is non-zero AND (when ApprovalEvidence is present)
//     equals one of the embedded bundle's ApprovalEvidence[*].PlanHash
//     values, OR equals the OutcomeDigest for subsystem-attributed
//     bundles where artifact == outcome.
//  5. OutcomeDigest is non-zero and matches the embedded bundle's
//     OutcomeDigest field.
//  6. Every inclusion proof verifies against its declared ChainHash.
//  7. If the embedded bundle is anchored: AnchorProof is non-nil; its
//     BundleID, TxHash, and BlockHeight match the embedded bundle's
//     AnchorTxHash + AnchorBlock; the package's AnchorTxHash +
//     AnchorBlockHeight cross-binding fields agree with the proof.
//  8. If TrustSnapshot is populated: every entry has a non-zero
//     BlockHeight, AND every entry's ProfileID is present in the
//     embedded bundle's TrustAssumptions list.
//  9. If the embedded bundle has policy decisions, the package's
//     PolicyDecisionDigest equals the canonical-JSON SHA-256 of the
//     embedded bundle's PolicyDecisions slice.
//  10. PluginVersions entries (when present) carry non-empty
//      PluginID + Version + ImplementationHash. Empty slice is
//      permitted for bundles that didn't dispatch through the plugin
//      registry, but a partially-populated entry is a structural
//      defect.
func VerifyPortablePackage(pkg *PortableEvidencePackage) error {
	if pkg == nil {
		return fmt.Errorf("evidence/portable: package is nil")
	}

	// 1. Version check.
	if pkg.Version != PortableEvidencePackageVersion {
		return fmt.Errorf("evidence/portable: unsupported version %q (expected %q)",
			pkg.Version, PortableEvidencePackageVersion)
	}

	// 2. Export hash integrity.
	computed, err := computePortableExportHash(pkg)
	if err != nil {
		return fmt.Errorf("evidence/portable: recompute export hash: %w", err)
	}
	if computed != pkg.ExportHash {
		return fmt.Errorf("evidence/portable: export hash mismatch (package tampered or non-canonical encoding)")
	}

	// 3. BundleData parses.
	if len(pkg.BundleData) == 0 {
		return fmt.Errorf("evidence/portable: empty BundleData")
	}
	var embedded EvidenceBundle
	if err := json.Unmarshal(pkg.BundleData, &embedded); err != nil {
		return fmt.Errorf("evidence/portable: BundleData not a valid EvidenceBundle: %w", err)
	}

	// 4. Plan hash. P1-005 closure: cross-bind to the embedded bundle's
	// approval evidence so swapping pkg.PlanHash AND rehashing
	// ExportHash is still caught.
	if pkg.PlanHash == [32]byte{} {
		return fmt.Errorf("evidence/portable: PlanHash is zero")
	}
	if err := verifyPortablePlanHashBinding(pkg, &embedded); err != nil {
		return err
	}

	// 5. Outcome digest matches the embedded bundle.
	if pkg.OutcomeDigest == [32]byte{} {
		return fmt.Errorf("evidence/portable: OutcomeDigest is zero")
	}
	if embedded.OutcomeDigest != pkg.OutcomeDigest {
		return fmt.Errorf("evidence/portable: OutcomeDigest does not match embedded bundle.OutcomeDigest")
	}

	// 6. Inclusion proofs.
	for i, proof := range pkg.InclusionProofs {
		p := proof
		if !VerifyMerkleInclusionProof(&p) {
			return fmt.Errorf("evidence/portable: inclusion proof %d failed verification", i)
		}
	}

	// 7. Anchor proof when bundle is anchored. P1-005 closure: extend
	// the BundleID match with TxHash + BlockHeight cross-bindings so
	// swapping just the anchor envelope is caught.
	if embedded.Anchor == AnchorStatusAnchored || embedded.Anchor == AnchorStatusVerified {
		if pkg.AnchorProof == nil {
			return fmt.Errorf("evidence/portable: anchored bundle missing AnchorProof")
		}
		if pkg.AnchorProof.BundleID != embedded.ID {
			return fmt.Errorf("evidence/portable: AnchorProof.BundleID %q does not match embedded bundle.ID %q",
				pkg.AnchorProof.BundleID, embedded.ID)
		}
		if embedded.AnchorTxHash != "" && pkg.AnchorTxHash != embedded.AnchorTxHash {
			return fmt.Errorf("evidence/portable: AnchorTxHash mismatch: package %q vs embedded bundle %q",
				pkg.AnchorTxHash, embedded.AnchorTxHash)
		}
		if embedded.AnchorBlock != 0 && pkg.AnchorBlockHeight != embedded.AnchorBlock {
			return fmt.Errorf("evidence/portable: AnchorBlockHeight mismatch: package %d vs embedded bundle %d",
				pkg.AnchorBlockHeight, embedded.AnchorBlock)
		}
	}

	// 8. Trust snapshot freshness + cross-binding to embedded
	// TrustAssumptions. P1-005 closure: a snapshot entry whose
	// ProfileID is NOT in the bundle's TrustAssumptions is either
	// fabricated (attacker injected) or stale (bundle list changed
	// after seal).
	embeddedProfiles := make(map[string]bool, len(embedded.TrustAssumptions))
	for _, ta := range embedded.TrustAssumptions {
		embeddedProfiles[ta.ProfileID] = true
	}
	for i, entry := range pkg.TrustSnapshot {
		if entry.BlockHeight == 0 {
			return fmt.Errorf("evidence/portable: trust snapshot entry %d has zero BlockHeight", i)
		}
		if len(embeddedProfiles) > 0 && !embeddedProfiles[entry.ProfileID] {
			return fmt.Errorf("evidence/portable: trust snapshot entry %d ProfileID %q not present in embedded bundle.TrustAssumptions (P1-005 cross-binding)",
				i, entry.ProfileID)
		}
	}

	// 9. Policy decision digest cross-binding. P1-005 closure: when
	// the embedded bundle has policy decisions, the package MUST
	// commit to their canonical hash. Tampering ANY decision in the
	// embedded bundle changes the digest; rehashing ExportHash alone
	// is insufficient to hide the tamper.
	expectedPolicyDigest, err := computePolicyDecisionDigest(embedded.PolicyDecisions)
	if err != nil {
		return fmt.Errorf("evidence/portable: recompute policy decision digest: %w", err)
	}
	if expectedPolicyDigest != pkg.PolicyDecisionDigest {
		return fmt.Errorf("evidence/portable: PolicyDecisionDigest mismatch (embedded bundle decisions differ from package commitment — tamper detected)")
	}

	// 10. PluginVersions structural checks. Empty slice is permitted
	// (subsystem-attributed bundles that bypass the plugin registry).
	// A populated entry MUST carry all three identity fields.
	for i, pv := range pkg.PluginVersions {
		if pv.PluginID == "" || pv.Version == "" || pv.ImplementationHash == "" {
			return fmt.Errorf("evidence/portable: PluginVersions[%d] is partially populated (id=%q version=%q implHash=%q)",
				i, pv.PluginID, pv.Version, pv.ImplementationHash)
		}
	}

	return nil
}

// HasReplayCapsule reports whether the package carries deterministic-
// replay material. platform-review-3 Epic 2.
func (pkg *PortableEvidencePackage) HasReplayCapsule() bool {
	return pkg != nil && len(pkg.ReplayCapsule) > 0 && string(pkg.ReplayCapsule) != "null"
}

// verifyPortablePlanHashBinding enforces the P1-005 plan-hash
// cross-binding: when the embedded bundle carries approval evidence
// with non-zero PlanHash entries, the portable package's PlanHash MUST
// match one of them. Subsystem-attributed bundles without approval
// evidence are permitted to use OutcomeDigest as PlanHash (artifact ==
// outcome semantics), so the check accepts that fallback when no
// approval entry is present. Empty embedded ApprovalEvidence + a
// PlanHash that doesn't match OutcomeDigest is rejected — the package
// claims a plan hash that the bundle cannot prove.
func verifyPortablePlanHashBinding(pkg *PortableEvidencePackage, embedded *EvidenceBundle) error {
	var nonZeroEntries int
	for _, ae := range embedded.ApprovalEvidence {
		if ae.PlanHash == [32]byte{} {
			continue
		}
		nonZeroEntries++
		if ae.PlanHash == pkg.PlanHash {
			return nil
		}
	}
	if nonZeroEntries > 0 {
		return fmt.Errorf("evidence/portable: PlanHash does not match any embedded bundle.ApprovalEvidence[*].PlanHash (P1-005 cross-binding)")
	}
	// Subsystem-attributed fallback: PlanHash may equal OutcomeDigest.
	if pkg.PlanHash == pkg.OutcomeDigest {
		return nil
	}
	return fmt.Errorf("evidence/portable: PlanHash has no binding witness in embedded bundle (no approval evidence and not equal to OutcomeDigest — P1-005 cross-binding)")
}

// computePortableExportHash computes the SHA-256 of all portable
// package fields except ExportHash and Signature. It uses the
// canonical JSON encoding so that the resulting hash is reproducible
// across runs and across implementations conforming to PORTABLE_SPEC.md.
//
// P1-005 closure (2026-05-02) extended the intermediate map with the
// new cross-binding fields. Adding fields here is a wire-format change
// that requires bumping PortableEvidencePackageVersion.
func computePortableExportHash(pkg *PortableEvidencePackage) ([32]byte, error) {
	// Build a deterministic intermediate representation that excludes
	// ExportHash and Signature.
	intermediate := map[string]any{
		"version":              pkg.Version,
		"bundleData":           json.RawMessage(pkg.BundleData),
		"planHash":             pkg.PlanHash,
		"outcomeDigest":        pkg.OutcomeDigest,
		"trustSnapshot":        pkg.TrustSnapshot,
		"inclusionProofs":      pkg.InclusionProofs,
		"anchorProof":          pkg.AnchorProof,
		"anchorTxHash":         pkg.AnchorTxHash,
		"anchorBlockHeight":    pkg.AnchorBlockHeight,
		"pluginVersions":       pkg.PluginVersions,
		"policyDecisionDigest": pkg.PolicyDecisionDigest,
		"replayCapsule":        json.RawMessage(pkg.ReplayCapsule),
	}
	canonical, err := canonicalJSON(intermediate)
	if err != nil {
		return [32]byte{}, err
	}
	return sha256.Sum256(canonical), nil
}
